setwd("simulated spots/")
library(Matrix.utils)
library(Seurat)
library(tidyverse)
library(magrittr)

pbmc.data <- Read10X(data.dir = "~/Downloads/filtered_gene_bc_matrices/hg19/")
pbmc <- CreateSeuratObject(counts = pbmc.data, project = "pbmc3k", min.cells = 3, min.features = 200)
pbmc[["percent.mt"]] <- PercentageFeatureSet(pbmc, pattern = "^MT-")
pbmc <- subset(pbmc, subset = nFeature_RNA > 200 & nFeature_RNA < 2500 & percent.mt < 5)
pbmc <- NormalizeData(pbmc, normalization.method = "LogNormalize", scale.factor = 10000)
pbmc <- FindVariableFeatures(pbmc, selection.method = "vst", nfeatures = 2000)
pbmc <- ScaleData(pbmc, features = all.genes)
pbmc <- ScaleData(pbmc, features = rownames(pbmc))
pbmc <- RunPCA(pbmc, features = VariableFeatures(object = pbmc))
pbmc <- FindNeighbors(pbmc, dims = 1:10)
pbmc <- FindClusters(pbmc, resolution = 0.5)
pbmc <- RunUMAP(pbmc, dims = 1:10)

celltype=pbmc@meta.data %>% rownames_to_column("cell")
celltype=celltype %>%mutate(comb_index=sample.int(900, 2638, replace = T))
celltype= celltype %>% group_by(comb_index) %>% mutate(prop=sample.int(100, n(), replace = F)) %>% mutate(prop=prop/sum(prop))

pbmc <- FindVariableFeatures(pbmc, selection.method = "vst", nfeatures = 500)

cnts=pbmc@assays$RNA@counts[VariableFeatures(pbmc),celltype$cell]
cnts_prop=cnts %*% diag(celltype$prop)
cnts_prop=t(cnts_prop)
celltype$comb_index=paste0("C", celltype$comb_index)
cnts_new=aggregate.Matrix(cnts_prop, celltype$comb_index)
cnts_new=round(cnts_new)
cnts_new=as.matrix(cnts_new)
cnts_new=t(cnts_new)
cnts_new %<>% as.data.frame() %>%rownames_to_column("gene")
data.table::fwrite(cnts_new, "simulated_spots.csv")
data.table::fwrite(celltype, "simulated_metadata.csv")
cnts=as.data.frame(as.matrix(cnts)) %>% rownames_to_column("cell")
data.table::fwrite(cnts, "original_counts.csv")
ref=AverageExpression(pbmc, slot="counts")
data.table::fwrite(as.data.frame(ref$RNA[VariableFeatures(pbmc),]), "reference.csv")

metadata1=celltype %>% dplyr::filter(comb_index %in% colnames(cnts_new)[-c(1)])
metadata1=metadata1 %>% select(comb_index, seurat_clusters, prop)
metadata1= metadata1 %>% group_by(seurat_clusters,comb_index) %>% summarise(prop=sum(prop))
metadata1=metadata1 %>% pivot_wider(names_from = comb_index, values_from = prop, values_fill = 0)
metadata1=metadata1[,c("seurat_clusters",colnames(cnts_new)[-c(1)] )]
data.table::fwrite(metadata1, "true_weights.csv")
